### ISSUE TITLE
Build of Projet

### ISSUE THREAD

**Issue by cgarrotti** [AFcPPe/AutoLoadGoods#1]
Hi ! I can build from VS2022 Version ?

**Comment by AFcPPe** [comment]
Hello!

Yes, in theory, you can build the project using Visual Studio 2022. Although the project was originally created with JetBrains Rider, Visual Studio should be able to compile it as well. However, please be aware that you may need to adjust the paths for the dependencies manually. This is because the paths are not managed dynamically through environment variables or other means in the current setup. So, make sure to check and update the reference paths in your project settings when setting up the project in Visual Studio.
